class ErrorHandler {
    fun handleError(error : Exception){
        // Behandle den Fehler oder die Ausnahme
    }
}